version: '3.8'
services:
  web:
    build:
      context: .
      target: dev  # specify the build target if needed
    ports:
      - "5002:5002"
    command: ["flask", "run", "--host=0.0.0.0", "--port=5002"]
