# Generated by Django 4.1.4 on 2022-12-28 15:11

from django.db import migrations, models
import herreweb_backend.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(default='No description added')),
                ('status', models.IntegerField(default=herreweb_backend.utils.ProjectStatus['RUNNING'])),
                ('image', models.ImageField(null=True, upload_to='')),
                ('rtd_url', models.CharField(max_length=200, null=True)),
                ('url', models.CharField(max_length=200, null=True)),
                ('visible', models.BooleanField(default=False)),
            ],
        ),
    ]
